#
# Contains the full stack of bidder3 (not including crosstalk, elk, mysql)
# Does contain zookeeper and kafka.
#

version: "3"

services:

#   zookeeper:
#     image: "zookeeper"
#     ports:
#     - "2181:2181"

#   kafka:
#     image: "ches/kafka"
#     environment:
#       ZOOKEEPER_IP: "zookeeper"
#     ports:
#     - "9092:9092"
#     depends_on:
#     - zookeeper

#   zerospike:
#     image: "jacamars/zerospike:v1"
#     environment:
#       BROKERLIST: "kafka:9092"
#     ports:
#     - "6000:6000"
#     - "6001:6001"
#     - "6002:6002"
#     - "7001:7001"
#     #    #volumes:
#     #    #  - "./cache.db:/cache.db"
#     #    depends_on:
#     #      - kafka
# #    command: bash -c "./wait-for-it.sh kafka:9092 -t 120 && sleep 1; ./zerospike"


  db:
    image: ploh/mysqlrtb
    ports:
    - "3305:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=rtb4free
    - MYSQL_DATABASE=rtb4free
    - MYSQL_USER=ben
    - MYSQL_PASSWORD=test
  web:
    image: ploh/rtbadmin_open
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
    - "3000:3000"
    environment:
    - CUSTOMER_NAME=RTB4FREE
    - RTB4FREE_DATABASE_HOST=localhost
    - RTB4FREE_DATABASE_PORT=3306
    - RTB4FREE_DATABASE_USERNAME=root
    - RTB4FREE_DATABASE_PASSWORD=none
    - RTB4FREE_DATABASE_NAME=rtb4free
    - RTB_CROSSTALK_REGION_HOSTS={"US" => "crosstalk"}
    - ELASTICSEARCH_ENABLE=false
    - ELASTICSEARCH_HOST=elastic1:9200
    - ELASTICSEARCH_KIBANA_URL=http://kibana:5601/


#   crosstalk:
#     image: "jacamars/crosstalk:v1"
#     environment:
#       REGION: "US"
#       GHOST: "elastic1"
#       AHOST: "elastic1"
#       BROKERLIST: "kafka:9092"
#       PUBSUB: "zerospike"
#       CONTROL: "8100"
#       JDBC: "jdbc:mysql://db/rtb4free?user=ben&password=test"
#     depends_on:
#     - kafka
#     - zerospike

#   elastic1:
#     image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
#     ports:
#     - "9200:9200"
#     - "9300:9300"
#     environment:
#     - discovery.type=single-node
#     - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
#     volumes:
#     - "./esdata1:/usr/share/elasticsearch/data"

#   #      networks:
#   #        - kafka_net
#   #        - control_net

#   logstash1:
#     image: docker.elastic.co/logstash/logstash:6.1.1
#     ports:
#     - "5044:5044"
#     environment:
#     - "XPACK_MONITORING_ELASTICSEARCH_URL=http://elastic1:9200"
#     - "XPACK_MONITORING_ENABLED=true"
#     - "LS_JAVA_OPTS=-Xmx1g"




# #  bidder:
# #    image: "jacamars/rtb4free:v1"
# #    environment:
# #      BROKERLIST: "kafka:9092"
# #      PUBSUB: "zerospike"
# #      EXTERNAL: "http://localhost:8080"
# #      ACCOUNTING: "accountingsystem"
# #      FREQGOV: "false"
# #      INDEXPAGE: "/index.html"
# #    ports:
# #    - "8080:8080"
# #    - "8155:8155"
# #    - "7379:7379"
# #    - "7000:7000"
# #    depends_on:
# #    - kafka
# #    - zerospike
# #    command: bash -c "./wait-for-it.sh kafka:9092 -t 120 && ./wait-for-it.sh zerospike:6002 -t 120 && sleep 1; ./rtb4free"
